spring.application.name=ex99-board-paging

#포트설정
server.port=8282

#오라클 접속 정보
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#로컬 DB
#spring.datasource.url=jdbc:oracle:thin:@localhost:1523/XEPDB1
#도커 DB
spring.datasource.url=jdbc:oracle:thin:@myOracle03:1521/XEPDB1
spring.datasource.username=boot_user
spring.datasource.password=1234

#JPA설정 : persistence.xml과 동일한 내용임 
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
# none, create, create-drop, update, validate 중 선택
spring.jpa.properties.hibernate.hbm2ddl.auto=update

#show sql data binding(하이버네이트6을 사용하므로 아래와같이 해야 로그가 정상적으로 출력됨)
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace